# Task 3

First, update the following cell to have a link to your Homework 1 GitHub repository:


**UPDATE THIS LINK:**

[https://github.com/rosemaryjuarez/eds220-hwk-1]()


In this task, make at least 5 commits at moments you think are adequate. We'll look at your repo to check commit history.

Add comments for all your code. Err on the side of commenting too much for now. 

Comments in each exercise and commits will count towards your grade.

This task covers topics we will see on Monday Oct. 9. The best strategy to solve it is to get together with your classmates and work on it together after Monday's lecture.


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

**description**: the dataset is on coral cover and number of “genera” in the Western Indian Ocean. Used to collect sample on coral bleaching. The data includes the coral reef locations, number of coral taxa, and climate change, water quality, human resource management and extraction variables for each 6.25km2 reef cell averaged over the 1998-2022 sampling period.  



**citation**: 
Tim McClanahan. (2023). Western Indian Ocean Coral Diversity. Knowledge Network for Biocomplexity. doi:10.5063/F1K35S3H.

**date of access**: 10/12/2023

**link**: https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Ae7d12a5a-f1a9-4a3e-aaa5-5222f67e799d

## 2
In the next code cell, import the pandas package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [3]:
import pandas as pd # importing pandas as pd

In [4]:
# importing coral data using url
coral_div = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Ae7d12a5a-f1a9-4a3e-aaa5-5222f67e799d')
# this will show all column names 
pd.set_option('display.max_columns', None) 
#use head() to see first 5
coral_div.head()

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.00781,0.541991,0.09475,0.008503,32.38792,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.00781,0.541991,0.09475,0.008503,32.38792,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.00781,0.541991,0.09475,0.008503,32.38792,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.00781,0.541991,0.09475,0.008503,32.38792,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.10547,0.690454,0.11400,0.008503,32.38792,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

a. how many rows and columns does it have?

b. what are the column names?

c. what are the data types of the columns?

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (see discussion section)

e. some inital info you are interested in. 

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

In [8]:
# a) there are 575 rows and 42 columns
coral_div.shape

(575, 42)

In [12]:
# b 
coral_div.columns

#column names are" PU_ID', 'PU_Lat', 'PU_Lon', 
#'Number_of_genera', 'Country', 'Ecoregion','Management', 
#'Habitat', 'Observer', 'Depth', 'Coralcover','SSTRateofRise', 
#'PARmax', 'Calcite', 'Dis_oxygen', 'mean.waveNRJ','Salinity_mean', 
#'andrello_reef_value', 'andrello_nutrients','mean.npp', 'TT_market_hrs', 
#'TT_pop_hrs', 'cumDHW', 'SST_Kurtosis','SST_Median', 'ChlorA_median', 
#'andrello_sediments', 'Current_vel_mean','Diff_attenuation', 'Grav_NP', 
#'Grav_NC', 'PH', 'SST_bimodality','SST_Skewness', 'ClimateStressModel', 'Netflow', 
#'Indegree','Outdegree', 'Retention', 'min_yr', 'max_yr', 'no_replicates'],

Index(['PU_ID', 'PU_Lat', 'PU_Lon', 'Number_of_genera', 'Country', 'Ecoregion',
       'Management', 'Habitat', 'Observer', 'Depth', 'Coralcover',
       'SSTRateofRise', 'PARmax', 'Calcite', 'Dis_oxygen', 'mean.waveNRJ',
       'Salinity_mean', 'andrello_reef_value', 'andrello_nutrients',
       'mean.npp', 'TT_market_hrs', 'TT_pop_hrs', 'cumDHW', 'SST_Kurtosis',
       'SST_Median', 'ChlorA_median', 'andrello_sediments', 'Current_vel_mean',
       'Diff_attenuation', 'Grav_NP', 'Grav_NC', 'PH', 'SST_bimodality',
       'SST_Skewness', 'ClimateStressModel', 'Netflow', 'Indegree',
       'Outdegree', 'Retention', 'min_yr', 'max_yr', 'no_replicates'],
      dtype='object')

In [14]:
# c 
coral_div.info()
#the data type of the objects are as follows in this output: integers, floats, and objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575 entries, 0 to 574
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PU_ID                575 non-null    int64
 1   PU_Lat               575 non-null    float64
 2   PU_Lon               575 non-null    float64
 3   Number_of_genera     575 non-null    int64
 4   Country              575 non-null    object
 5   Ecoregion            575 non-null    object
 6   Management           575 non-null    object
 7   Habitat              530 non-null    object
 8   Observer             575 non-null    object
 9   Depth                575 non-null    float64
 10  Coralcover           575 non-null    int64
 11  SSTRateofRise        575 non-null    float64
 12  PARmax               575 non-null    float64
 13  Calcite              575 non-null    float64
 14  Dis_oxygen           575 non-null    float64
 15  mean.waveNRJ         575 non-null    float64
 16  Salinity_mean        575 non-null    float64
 17  andrello_reef_value  575 non-null    int64
 18  andrello_nutrients   575 non-null    float64
 19  mean.npp             575 non-null    float64
 20  TT_market_hrs        575 non-null    float64
 21  TT_pop_hrs           575 non-null    float64
 22  cumDHW               575 non-null    float64
 23  SST_Kurtosis         575 non-null    float64
 24  SST_Median           575 non-null    float64
 25  ChlorA_median        575 non-null    float64
 26  andrello_sediments   575 non-null    float64
 27  Current_vel_mean     567 non-null    float64
 28  Diff_attenuation     575 non-null    float64
 29  Grav_NP              575 non-null    float64
 30  Grav_NC              575 non-null    float64
 31  PH                   575 non-null    float64
 32  SST_bimodality       575 non-null    float64
 33  SST_Skewness         575 non-null    float64
 34  ClimateStressModel   575 non-null    float64
 35  Netflow              575 non-null    float64
 36  Indegree             575 non-null    float64
 37  Outdegree            575 non-null    float64
 38  Retention            575 non-null    float64
 39  min_yr               575 non-null    int64
 40  max_yr               575 non-null    int64
 41  no_replicates        575 non-null    int64
dtypes: float64(30), int64(7), object(5)
memory usage: 188.8+ KB

In [15]:
# d already set column names as visible in question 4
coral_div.head(8)

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,45,0.019214,54.747001,0.001075,4.7495,3.714321,35.167646,0,8.388602,1139.112671,1.383333,0.366667,24.133263,-0.803330,27.435,0.465182,53540.007810,0.541991,0.09475,0.008503,32.387920,8.2175,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,48,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.700521,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,41,0.020051,55.395000,0.001747,4.7510,3.270938,35.102688,0,6.731860,1126.355957,1.383333,0.366667,25.342901,-0.793681,27.455,0.592692,38477.105470,0.690454,0.11400,0.008503,32.387920,8.2180,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,49,0.021358,54.935499,0.001744,4.7540,2.857747,35.106329,0,2.645199,1150.677856,1.783333,0.333333,30.265219,-0.795494,27.525,0.656533,3224.024414,0.561659,0.10500,0.512126,19.634828,8.2185,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [6]:
# e)

# im interested to see more on the relationship between habitat, coral cover, and salinity.

#commit # 1

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

The difference is that integers are whole numbers, and they tend to only be used for discrete variables. While float64 are for numbers with decimals. This means we can have a long range of infinite numbers (continuous).

## 5

The `Country` column indicates the country of reef location. Explain in your words what is the ouput of `coral_div.Country` and `coral_div.Country.unique()`.

In [22]:
coral_div.Country
coral_div.Country.unique()

array(['Tanzania', 'Mozambique', 'Kenya', 'Reunion', 'Comoros', 'Mayotte',
       'French Southern Territories', 'Madagascar', 'Seychelles',
       'South Africa', 'Mauritius'], dtype=object)

when running `coral_div.Country`, I received a series of all the recorded countries. Meanwhile, `coral_div.unique` gives me an output that shows which countries are within the list.

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: use the `len` Python function. Not sure what `len` does? Use `?`.

In [29]:
# the Observers column tells us the name of the observers who collectged the data. 

len(coral_div.Observer.unique())

#the number of unique observers are 16.

16

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6km reef cell surveyed. What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

In [32]:
coral_div[coral_div['Coralcover'] >= 50]

#this is selecting coral cover that is about 50% or more, using indexing and conditionals to achieve this.

# commit #2

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,mean.waveNRJ,Salinity_mean,andrello_reef_value,andrello_nutrients,mean.npp,TT_market_hrs,TT_pop_hrs,cumDHW,SST_Kurtosis,SST_Median,ChlorA_median,andrello_sediments,Current_vel_mean,Diff_attenuation,Grav_NP,Grav_NC,PH,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
39,220,39.233916,-6.658981,17,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.000000,50,0.019705,54.497002,0.005484,4.76950,2.580136,35.115938,1999,5.461948,1225.299561,0.550000,0.166667,31.304594,-1.050763,27.5125,0.536352,376.639374,0.573046,0.16750,2.088395,2482.528053,8.2160,0.527900,-0.171423,0.62130,-0.443779,127.50,62.25,204.75,2016,2016,1
40,220,39.233916,-6.658981,19,Tanzania,East African Coral Coast,UnfishedLow,Slope,Tim,2.833333,50,0.019705,54.497002,0.005484,4.76950,2.580136,35.115938,1999,5.461948,1225.299561,0.550000,0.166667,31.304594,-1.050763,27.5125,0.536352,376.639374,0.573046,0.16750,2.088395,2482.528053,8.2160,0.527900,-0.171423,0.62130,-0.443779,127.50,62.25,204.75,2012,2019,3
41,221,39.256374,-6.658981,25,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,10.000000,50,0.019248,54.117250,0.002964,4.76925,2.580136,35.123019,1999,5.461948,1225.299561,0.550000,0.166667,30.428848,-1.048609,27.5050,0.471443,376.639374,0.676979,0.12875,2.088395,2482.528053,8.2155,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
42,221,39.256374,-6.658981,19,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,10.000000,50,0.019248,54.117250,0.002964,4.76925,2.580136,35.123019,1999,5.461948,1225.299561,0.550000,0.166667,30.428848,-1.048609,27.5050,0.471443,376.639374,0.676979,0.12875,2.088395,2482.528053,8.2155,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
43,221,39.256374,-6.658981,12,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.000000,50,0.019248,54.117250,0.002964,4.76925,2.580136,35.123019,1999,5.461948,1225.299561,0.550000,0.166667,30.428848,-1.048609,27.5050,0.471443,376.639374,0.676979,0.12875,2.088395,2482.528053,8.2155,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,4039,48.082322,-13.553193,27,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Arielle,6.733333,50,0.024337,56.205000,0.000539,4.62450,0.012061,34.864458,15,0.031631,1351.801636,5.950000,0.183333,17.674561,-1.104230,28.1300,0.465219,237.490143,0.053012,0.15100,0.819690,0.648977,8.2025,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2017,2019,3
304,4039,48.082322,-13.553193,20,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,D'Agata,6.000000,50,0.024337,56.205000,0.000539,4.62450,0.012061,34.864458,15,0.031631,1351.801636,5.950000,0.183333,17.674561,-1.104230,28.1300,0.465219,237.490143,0.053012,0.15100,0.819690,0.648977,8.2025,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2016,2016,2
305,4039,48.082322,-13.553193,21,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Julien,5.000000,50,0.024337,56.205000,0.000539,4.62450,0.012061,34.864458,15,0.031631,1351.801636,5.950000,0.183333,17.674561,-1.104230,28.1300,0.465219,237.490143,0.053012,0.15100,0.819690,0.648977,8.2025,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2016,2016,1
306,4039,48.082322,-13.553193,33,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Nyawira,5.000000,50,0.024337,56.205000,0.000539,4.62450,0.012061,34.864458,15,0.031631,1351.801636,5.950000,0.183333,17.674561,-1.104230,28.1300,0.465219,237.490143,0.053012,0.15100,0.819690,0.648977,8.2025,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2015,2015,1
514,6064,40.603847,-12.496246,30,Mozambique,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,8.000000,51,0.022442,57.038000,0.000572,4.40500,0.121287,35.027771,38,0.596784,794.522034,3.433333,0.366667,34.654408,-1.073709,27.3750,0.404617,2850.314453,0.091254,0.09500,0.006355,2.553257,8.2030,0.529942,-0.145626,0.68105,0.116857,54.75,54.25,126.50,2015,2015,1

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania.

In [8]:
# solve exercise here

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (PSS) (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Select this data.

In [9]:
# solve exercise here

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017.

In [10]:
# solve exercise here

## 11
Use `iloc` to select rows 95 throuhg 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean`. Are you indexing from 0?

In [11]:
# solve exercise here

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

*Update this markdown cell with your answer.*

## 13
Run `subset.isna().any()`. Explain what this code does and what the output represents. HINT: It could be helpful to check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

*Update this markdown cell with your answer.*

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. HINT: you can use your answer for 9.

In [12]:
# solve exercise here